### ISSUE TITLE
What's the reason for Bluetooth permission?

### ISSUE THREAD

**Issue by qbait** [flutuate/mixpanel#11]
Hi,
I've noticed permission in `AndroidManifest`.
`<uses-permission android:name="android.permission.BLUETOOTH" />`

What's the reason?

**Comment by lamkr** [comment]
Hello!
Although it is optional, I chose to keep the permission for those who need events related to the state of Bluetooth (see the suggestion at https://developer.mixpanel.com/docs/android#step-2---add-permissions-to-your-androidmanifestxml).
