### ISSUE TITLE
iOS properties not working

### ISSUE THREAD

**Issue by dagovalsusa** [flutuate/mixpanel#12]
Hello,
I have a problem with iOS, with the example code _mixpanel.track (event, property) on iOS the object properties are not logged and arrive empty but with Android they work fine.

Someone knows why? Thanks

**Comment by shouvikgr** [comment]
Have the same issue, I actually ended up using the http-apis for the IOS system. The problem is now I don't get device properties.

**Comment by gunantosteven** [comment]
No update ? same issue here. I don't get device properties on iOS as well.

**Comment by lamkr** [comment]
Solved by @gunantosteven, please, see #14

**Comment by Limbou** [comment]
@lamkr The solution you mentioned will only work for String values, which doesn't have to be the case. These are all types that Mixpanel iOS sdk supports (from the documentation): `/// MixpanelType can be either String, Int, UInt, Double, Float, Bool, [MixpanelType], [String: MixpanelType], Date, URL, or NSNull.`

**Comment by gunantosteven** [comment]
> @lamkr The solution you mentioned will only work for String values, which doesn't have to be the case. These are all types that Mixpanel iOS sdk supports (from the documentation): `/// MixpanelType can be either String, Int, UInt, Double, Float, Bool, [MixpanelType], [String: MixpanelType], Date, URL, or NSNull.`

maybe you can help, see #15

**Comment by Limbou** [comment]
Please take a look at #16

**Comment by gunantosteven** [comment]
> Please take a look at #16

It should be merged

**Comment by Limbou** [comment]
This issue can be closed as it is fixed in #16
