### ISSUE TITLE
Missing feature for reporting user properties

### ISSUE THREAD

**Issue by tnovoselec** [flutuate/mixpanel#17]
Hello!
We're currently using Mixpanel for our Native apps, and we really like the feature for reporting user properties through [People](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.People.html#set-java.lang.String-java.lang.Object-) object.
Is this feature also planned to be supported by Flutter SDK?

**Comment by lamkr** [comment]
> Hello!
> We're currently using Mixpanel for our Native apps, and we really like the feature for reporting user properties through [People](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.People.html#set-java.lang.String-java.lang.Object-) object.
> Is this feature also planned to be supported by Flutter SDK?

I'm sorry, I'm very busy, I don't have an estimated date

**Comment by danypata** [comment]
@lamkr is it possible to ad me as a collaborator to this project. I've added the People api and I can push it to the repo. Let me know your thoughts.

**Comment by lamkr** [comment]
> @lamkr is it possible to ad me as a collaborator to this project. I've added the People api and I can push it to the repo. Let me know your thoughts.

Hello, @danypata, I liked the idea. I also noticed that you forked the repository. You can contribute with the pull request of your repo.

**Comment by danypata** [comment]
@lamkr If you have any time, feel free to review my PR.

**Comment by maurodibert** [comment]
@danypata hi! I was about to do the same! Is there any update on this?

**Comment by danypata** [comment]
@maurodibert I've created a PR for the people api, it's there so it just need a review and merge maybe. If not you can pull it from my branch.

**Comment by maurodibert** [comment]
Thanks @danypata ! Awesome work! :pray:

**Comment by GuillaumeFerron** [comment]
+1 here, thank you @danypata , @lamkr if you could have a look if you have a bit of time, that feature would be really helpful 💪 
Great package by the way!

**Comment by lamkr** [comment]
Please, @danypata, review your PR 'cause it is conflicting with another commit. Thank you!

**Comment by danypata** [comment]
@lamkr Done. You can check the PR.

**Comment by duncanhall** [comment]
Hi @lamkr / @danypata - is there an update on when / if this is being released? I can see the PR seems to have been merged, but the latest release is still around 2 months ago? If there is something specific I can do to help get this functionality released, let me know.

**Comment by danypata** [comment]
@duncanhall I've added the functionality and it seems that it's merged but i think @lamkr should release it, I'm not sure what release process he has.

**Comment by lamkr** [comment]
Hi, all! Version 1,1.6 with all changes released now. Please, checking it
