### ISSUE TITLE
Any Workaround for web

### ISSUE THREAD

**Issue by mrinaljain** [flutuate/mixpanel#20]
I am using this plugin for ios and android but it gives error for web build .
Is there ant workaround ?

**Comment by maurodibert** [comment]
Me too!

**Comment by lamkr** [comment]
I would like it very much, but the Mixpanel SDK for Android/iOS uses platform-specific functionalities, so it is not possible to create any workaround for web from current sources.
It is possible to implement a new interface that makes use of the Mixpanel Rest API (see https://developer.mixpanel.com/reference/overview), but in that case, the methods contracts will have to be changed drastically.
