### ISSUE TITLE
MissingPluginException(No implementation found for method getInstance on channel flutuate.io/plugins/mixpanel)

### ISSUE THREAD

**Issue by shouvikgr** [flutuate/mixpanel#4]
`   MixpanelAPI _mixpanel =  await MixpanelAPI.getInstance('#######de96ddaf7711#######');
`   

Flutter doctor output:

> [✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F101, locale en)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
> [✓] Android Studio (version 3.3)
> [!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
> [✓] VS Code (version 1.41.1)
> [✓] VS Code (version 1.45.1)
> [✓] Connected device (1 available)

**Comment by flutuate** [comment]
Please, use new version 1.1.0. Thank you!

**Comment by shouvikgr** [comment]
This issue still exists on IOS but for a build I am using from another source.

https://github.com/brauliolomeli/mixpanel

**Comment by shouvikgr** [comment]
The branch that you have pushed, doesn't install on IOS which I have filed a bug for.

**Comment by flutuate** [comment]
Please, try v1.1.1
