### ISSUE TITLE
Error installing on IOS (Error installing Mixpanel-swift)

### ISSUE THREAD

**Issue by shouvikgr** [flutuate/mixpanel#7]
[!] Error installing Mixpanel-swift
[!] /usr/bin/git clone https://github.com/mixpanel/mixpanel-swift.git /var/folders/s9/kxfstn8x20s66ppymrh_c80h0000gp/T/d20200616-23431-acf84m --template= --single-branch --depth 1 --branch v2.6.12

Cloning into '/var/folders/s9/kxfstn8x20s66ppymrh_c80h0000gp/T/d20200616-23431-acf84m'...
warning: Could not find remote branch v2.6.12 to clone.
fatal: Remote branch v2.6.12 not found in upstream origin

**Comment by flutuate** [comment]
Please, try v1.1.1
