### ISSUE TITLE
Why "Flutuate.io Mixpanel Plugin Event" is stored in mixpanel "flows"

### ISSUE THREAD

**Issue by sultanmyrza** [flutuate/mixpanel#9]
When I open mixpanel flows it shows me "Flutuate.io Mixpanel Plugin Event" too much
here is an [example](https://imgur.com/a/uPgMVwr)

Are you sending Mixpanel Plugin Event on native side every time when I instantiate new Instace?

**Comment by lamkr** [comment]
Hi, sultanmyrza. 
It is the example project that sends this event, please, see main.dart:127 (_MyAppState.trackEvent()).
Are using it to run your tests? If yes, comment or change the source code during your tests.
